language: node_js
node_js: 
  - "8"

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "qibotian"
  - git config user.email "hashcoder@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${9ab6ab0be45343d36565c90555a60b25f4a0a8cf}@${QBT_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-resource
env:
 global:
   - QBT_REF: qibotian/qibotian.github.io.git