language: node_js
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install
script:
- hexo g
after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "qibotian"
- git config user.email "hashcoder@163.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - blog-source
env:
  global:
  - GH_REF: github.com/qibotian/qibotian.github.io.git
addons:
  ssh_known_hosts:
  - 59.110.124.76
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 59.110.124.76\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@59.110.124.76 -o StrictHostKeyChecking=no 'cd ~/hexo_blog/qibotian.github.io && git pull && hexo g &'
- chmod 777 ~/hexo_blog/qibotian.github.io/*
