--- 
after_script: 
  - ./_travis.sh
after_success: ~
before_install: 
  - "npm install -g gulp"
  - "sudo apt-get install libnotify-bin"
before_script: 
  - "export TZ='Asia/Shanghai'"
  - "npm install -g gulp"
  - "chmod +x _travis.sh"
branches: 
  only: 
    - blog-source
cache: 
  directories: 
    - node_modules
env: 
  global: 
    - 
      GH_REF: github.com/qibotian/qibotian.github.io.git
install: 
  - "npm install"
language: node_js
node_js: stable
script: 
  - "hexo clean && hexo g"
  - gulp
sudo: false
